name: update-latest-challenge
run-name: update the latest challenge from AoC
on:
  workflow_dispatch:
  schedule:
    - cron: "15 0 1-12 12 *"
permissions:
  contents: write
jobs:
  update-latest-challenge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install deps
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip

      - name: Install UV
        run: pip install uv --break-system-packages

      - name: Install Python deps
        run: uv sync

      - name: Download challenge
        env:
          ADVENT_OF_CODE: ${{ secrets.ADVENT_OF_CODE }}
        run: |
          cd src
          day="$(date +'%-d')"
          uv run python prep.py --download $day

      - name: Commit changes
        run: |
          git config --global user.email "david@newh.am"
          git config --local user.name "updater-bot"
          day="$(date +'%-d')"
          git add -A
          git status
          git commit -m "Challenge day $day"
          git push
